image: ubuntu:focal

variables:
  GIT_STRATEGY: clone
  DEBIAN_FRONTEND: noninteractive

stages:
  - run-tests

run-tests:
  stage: run-tests
  artifacts:
    when: always
    paths:
      - log/
  before_script:
    - |
      runcmd() {
        local logfile="${1}"
        shift
        if ! $* >"${logfile}" 2>&1; then
            echo "Execution of '$*' failed:"
            cat ${logfile}
            false
        fi
      }
    - mkdir -p log
    - runcmd log/update.txt apt update
    - runcmd log/upgrade.txt apt upgrade -y
    - runcmd log/install.txt apt install -y --no-install-suggests --no-install-recommends 
      git 
      asn1c 
      build-essential 
      cmake 
      curl 
      libarchive-dev 
      libboost-dev 
      libboost-filesystem-dev 
      libboost-log-dev
      libboost-program-options-dev 
      libcurl4-openssl-dev 
      libpthread-stubs0-dev 
      libsodium-dev 
      libsqlite3-dev 
      libssl-dev 
      python3 
      net-tools 
      python3-dev 
      python3-openssl 
      python3-venv 
      sqlite3 
      valgrind 
      clang 
      clang-format-11 
      clang-tidy-11 
      libostree-dev 
      ostree
    - runcmd log/submodule.txt git submodule update --init --recursive
  script:
    - mkdir build && cd build
    # Enable BUILD_OSTREE or else build fails
    - runcmd ../log/cmake.txt cmake .. -DBUILD_OSTREE:BOOL=ON
    - runcmd ../log/make.txt make -j4
    - runcmd ../log/build_tests.txt make -j4 build_tests
    - runcmd ../log/check-format.txt make -j4 check-format
    # Requires "|| true" for pipeline to not fail and end due to current errors
    - runcmd ../log/clang-tidy.txt make -j4 -k clang-tidy || true
    # CTEST_OUTPUT_ON_FAILURE=1 enables debug output
    # Not allowing parallel jobs, can cause some tests to not run and ruins order of output
    - runcmd ../log/test.txt make test CTEST_OUTPUT_ON_FAILURE=1
