[provision]
provision_path = "credentials.zip"
primary_ecu_hardware_id = "local-fake"

[uptane]
secondary_config_file = "posix-secondary-config.json"

[logger]
loglevel = 1

[storage]
path = "storage"

[pacman]
type = "none"
images_path = "storage/images"
